# Generated by Django 3.0.6 on 2020-05-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=300)),
                ('emp_mailid', models.CharField(max_length=300)),
                ('client_company_name', models.CharField(max_length=300)),
                ('client_location', models.CharField(max_length=300)),
                ('client_cname', models.CharField(max_length=300)),
                ('client_number', models.CharField(max_length=300)),
                ('client_address', models.CharField(max_length=3000)),
            ],
        ),
    ]
