# Generated by Django 3.0.6 on 2020-05-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empdetails',
        ),
    ]
