# Generated by Django 3.0.6 on 2020-05-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_empdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='empdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=300)),
                ('emp_name', models.CharField(max_length=300)),
                ('emp_mailid', models.CharField(max_length=300)),
                ('emp_batch', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
