# Generated by Django 3.0.6 on 2020-05-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_empdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientdetails1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=300)),
                ('emp_mailid', models.CharField(max_length=300)),
                ('client_company_name', models.CharField(max_length=300)),
                ('client_company_type', models.CharField(max_length=300)),
                ('client_address', models.CharField(max_length=3000)),
                ('client_package_details', models.CharField(max_length=300)),
                ('client_package_code', models.CharField(max_length=300)),
                ('client_students_count', models.CharField(max_length=300)),
                ('academic_year', models.CharField(max_length=300)),
                ('amount_to_be_paid', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='empdetails',
        ),
    ]
