# Generated by Django 3.0.6 on 2020-05-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200526_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientdetails',
        ),
    ]
